export enum ProductType{
    PALLET = 'PALETA',
    ANGLEBAR = 'KĄTOWNIK',
    SCOBS = 'TROCINY',
    PALLET_SOLID = 'PALETA SOLID',
    PALLET_ENGLISH = 'PALETA ANGIELSKA',
    PALLET_SKID = 'PALETA PŁOZOWA'
}